#Do not use tabs in yaml file, use 2 or 4 spaces for indentation


#samples
samples: "config/samples_test.tsv"

#fastq: "../data"

# either reference is given
ref: "" #"/home/rosa/SequencingAnalysis_Proj/Project2/data/chr22_with_ERCC92.fa"
ref_anno: "" #"/home/rosa/SequencingAnalysis_Proj/Project2/data/chr22_with_ERCC92.gtf"
# or wgs data for de novo assembly
# path to folder and sample name
wgs_data: "assembly/SRR13282500_Other_Sequencing_of_Shigella_flexneri_2a"

# optional contaminations to be removed
contaminations: "" #"config/contaminations.tsv"

## path to group assignment tsv for DEG
group_assignment: "example/samples_sheet_2M.tsv"

## use trimmed or raw reads
RNA_trimmed: False
WGS_trimmed: False
#tool parameters
software:
  hisat2:
    threads: 1
  star:
    indx_threads: 1
    align_threads: 1
    align_extra: ""
  feature_counts:
    threads: 1
  cutadapt:
    adapters: "-a AGAGCACACGTCTGAACTCCAGTCAC -g AGATCGGAAGAGCACACGT -A AGAGCACACGTCTGAACTCCAGTCAC -G AGATCGGAAGAGCACACGT"
    extra: "--minimum-length 1 -q 20"
    threads: 1
  kraken2:
    database: "/home/rosa/SequencingAnalysis/FinalProject/database/k2_viral_20230314"
    threads: 1
  seqtk:
    threads: 1
    reads: 10000
  megahit:
    threads: 1
  bowtie2:
    threads: 1
  samtools:
    threads: 1
    consensus:
      min_depth: 5  # samtools paramter d : making a call when specfified depth d is presented
  prokka:
    cpus: 2 # normally 8 cpus
  busco:
    threads: 1
  quast:
    extra: ""
  consensus:
    min_depth: 5  # samtools paramter d : making a call when specfified depth d is presented
    min_coverage: 0.9
  compleasm:
    threads: 1
  DEG:
    alpha: 0.05
    topn: 50  # number of the top genes with highest fold change visualized in the heatmap
  clustalo:
      threads: 1
