#Do not use tabs in yaml file, use 2 or 4 spaces for indentation


#samples
samples: "config/samples.tsv"

#fastq: "../data"

# either reference is given
ref: "" #data/chr22_with_ERCC92.fa"
ref_anno: "" # "data/chr22_with_ERCC92.gtf"
# or wgs data for de novo assembly
# path to folder and sample name
wgs_data: "assembly/SRR13282500_Other_Sequencing_of_Shigella_flexneri_2a"

# optional contaminations to be removed
contaminations: "" #"config/contaminations.tsv"



## use trimmed or raw reads
use_trimmed: True

#tool parameters
software:
  star:
    indx_threads: 1
    align_threads: 1
    align_extra: ""
  cutadapt:
    adapters: "-a AGAGCACACGTCTGAACTCCAGTCAC -g AGATCGGAAGAGCACACGT -A AGAGCACACGTCTGAACTCCAGTCAC -G AGATCGGAAGAGCACACGT"
    extra: "--minimum-length 1 -q 20"
    threads: 1
  kraken2:
    database: "/home/rosa/SequencingAnalysis/FinalProject/database/k2_viral_20230314"
    threads: 1
  seqtk:
    threads: 1
    reads: 10000
  megahit:
    threads: 1
  bowtie2:
    threads: 1
  samtools:
    threads: 1
  prokka:
    cpus: 2 # normally 8 cpus
  busco:
    threads: 1
  quast:
    extra: ""
  OGS:
    min_coverage: 0.9