#Do not use tabs in yaml file, use 2 or 4 spaces for indentation


#samples
samples: "config/samples.tsv"

#fastq: "../data"

# either reference is given
ref: "/code/AppliedSequenceAnalysis/SequencingAnalysis/FinalProject/reference/shigella_flexneri.fasta"
ref_anno: "/code/AppliedSequenceAnalysis/SequencingAnalysis/FinalProject/reference/shigella_flexneri.gff"
# or wgs data for de novo assembly
# path to folder and sample name
wgs_data: "" #"assembly/SRR13282500_Other_Sequencing_of_Shigella_flexneri_2a"

# optional contaminations to be removed
contaminations: "" #"contaminations/contaminations.fasta"

## path to group assignment tsv for DEG
group_assignment: "example/samples_sheet_2M.tsv"

## use trimmed or raw reads
RNA_trimmed: True
WGS_trimmed: True
#tool parameters
software:
  fastqc:
    threads: 4
  hisat2:
    threads: 4
  feature_counts:
    threads: 4
  cutadapt:
    adapters: "-a AGAGCACACGTCTGAACTCCAGTCAC -g AGATCGGAAGAGCACACGT -A AGAGCACACGTCTGAACTCCAGTCAC -G AGATCGGAAGAGCACACGT"
    extra: "--minimum-length 1 -q 20"
    threads: 4
  kraken2:
    database: "/code/AppliedSequenceAnalysis/SequencingAnalysis/FinalProject/database/k2_viral_20230605"
    threads: 4
  seqtk:
    threads: 4
    reads: 10000
  megahit:
    threads: 4
  bowtie2:
    threads: 4
  samtools:
    threads: 4
    consensus:
      min_depth: 5  # samtools paramter d : making a call when specfified depth d is presented
  prokka:
    cpus: 2 # normally 8 cpus
  quast:
    extra: ""
  FilterGenes:
    min_coverage: 0.9
  compleasm:
    threads: 4
  DEG:
    alpha: 0.05
    topn: 50  # number of the top genes with highest fold change visualized in the heatmap
  clustalo:
      threads: 4
